[package]
name = "coins"
version = "0.1.0"
authors = ["Oleksandr Otenko <oleksandr.o.otenko@oracle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
